export const LOAD_ARTICLES_REQUEST = "LOAD_ARTICLES_REQUEST";
export const LOAD_ARTICLES_SUCCESS = "LOAD_ARTICLES_SUCCESS";
export const LOAD_ARTICLES_FAILURE = "LOAD_ARTICLES_FAILURE";

export const LOAD_ARTICLE_BY_SLUG_REQUEST = "LOAD_ARTICLE_BY_SLUG_REQUEST";
export const LOAD_ARTICLE_BY_SLUG_SUCCESS = "LOAD_ARTICLE_BY_SLUG_SUCCESS";
export const LOAD_ARTICLE_BY_SLUG_FAILURE = "LOAD_ARTICLE_BY_SLUG_FAILURE";
